### ISSUE TITLE
Error while reading the input data

### ISSUE THREAD

**Issue by ybpaopao** [Necolizer/Facial-Prior-Based-FOMM#2]
Hi, I'm interested in your work. However, I encountered some problems when I re-produce your code. Does the numbers of detected key-points remain the same after I run the kpmaker.py? I meet a problem "RuntimeError: stack expects each tensor to be equal size, but got [18, 2] at entry 0 and [2] at entry 1" in the code line "for x in dataloader:". I have checked the code, and one possible reason may be the different numbers of detected facial key-points. So, could you kindly tell me how to solve the problem? Have a nice day!

**Comment by Necolizer** [comment]
Hi @ybpaopao , does the problem still exist? Seems that you solved it as this issue was closed? Please let us know if you still encounter this problem, thx.
