### ISSUE TITLE
About Driving Videos Selection.

### ISSUE THREAD

**Issue by xiejiachen** [Necolizer/Facial-Prior-Based-FOMM#3]
May I have an ask about:
Regarding with the MEGC, how the training video source you selected, such as :

1. For each output.mp4, training a model.
2. Training with all given data with specific emotions, and predict with each source image.

**Comment by Necolizer** [comment]
@xiejiachen Sry for my late reply. We took all the samples in three datasets for training, excluding all the source videos (driving videos) for testing in MEGC2021. Simply all-in, without grouping them by emotion types. Pridictions were made according to each pair of driving video and target face.
