### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Forgetwlb** [Necolizer/Facial-Prior-Based-FOMM#4]
paper下载不了吗，大佬？

**Comment by Necolizer** [comment]
@Forgetwlb 不是大佬不是大佬，但论文可以下载啊，我这边点进去看到还能下载，你要不再尝试一下？

https://dl.acm.org/doi/10.1145/3474085.3479211

**Comment by Necolizer** [comment]
> @Forgetwlb 不是大佬不是大佬，但论文可以下载啊，我这边点进去看到还能下载，你要不再尝试一下？
> 
> https://dl.acm.org/doi/10.1145/3474085.3479211

有可能是因为您所在的机构没有购买ACM Digital Library？这似乎有点难办……因为这篇短论文是在时间紧迫的比赛期间撰写的，并没有arxiv版本。我也不太确定直接通过邮件私发会不会违反ACM Digital Library的相关规定。

**Comment by Forgetwlb** [comment]
非常感谢！！！！我们学校买了，但有些ACM MM的会议不知道是不是没买全，有些论文能直接下载，但有些又要解锁，所以麻烦您了！！！我开始好好研究这个论文了，暖心。
