### ISSUE TITLE
In the code, which function is the Region-Focusing Module, not found?

### ISSUE THREAD

**Issue by flamefangz** [Necolizer/Facial-Prior-Based-FOMM#5]

**Comment by Necolizer** [comment]
Hi @flamefangz , you can refer to [make](https://github.com/Necolizer/Facial-Prior-Based-FOMM/blob/main/make.py) (imported by [keypoint_detector](https://github.com/Necolizer/Facial-Prior-Based-FOMM/blob/main/modules/keypoint_detector.py)) in this repo for our implementation of Region-Focusing Module with Eq (4), (5) and (6) in this paper.
